-- ============================================================
-- TABELAS BASE DO SISTEMA DE ESTACIONAMENTO
-- Execute este script no SQL Editor do Supabase
-- ============================================================

-- 0. EMPRESAS (referenciada pela configuracao e pelos tickets)
CREATE TABLE IF NOT EXISTS public.empresas (
    id SERIAL PRIMARY KEY,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    razao_social VARCHAR(200) NOT NULL,
    nome_fantasia VARCHAR(200) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(200),
    endereco TEXT,
    cidade VARCHAR(100),
    estado VARCHAR(2),
    cep VARCHAR(10),
    ativo BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    alterado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 1. CONFIGURACAO DO ESTACIONAMENTO
CREATE TABLE IF NOT EXISTS public.configuracao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_estacionamento TEXT NOT NULL DEFAULT 'Estaciona Parking',
    cnpj TEXT,
    telefone TEXT,
    endereco TEXT,
    cidade TEXT,
    estado TEXT,
    cep TEXT,
    total_vagas INT NOT NULL DEFAULT 20,
    vagas_carro INT NOT NULL DEFAULT 0,
    vagas_moto INT NOT NULL DEFAULT 0,
    vagas_carro_grande INT NOT NULL DEFAULT 0,
    vagas_caminhonete INT NOT NULL DEFAULT 0,
    valor_primeira_hora NUMERIC NOT NULL DEFAULT 5.0,
    valor_hora_adicional NUMERIC NOT NULL DEFAULT 3.0,
    valor_mensal NUMERIC NOT NULL DEFAULT 150.0,
    horario_abertura TEXT,
    horario_fechamento TEXT,
    cabecalho_ticket TEXT,
    rodape_ticket TEXT,
    ticket_exibir_cnpj BOOLEAN NOT NULL DEFAULT true,
    ticket_exibir_contato BOOLEAN NOT NULL DEFAULT true,
    ticket_formato_papel TEXT NOT NULL DEFAULT '80mm',
    ticket_exibir_codigo_barras BOOLEAN NOT NULL DEFAULT true,
    bloquear_sem_vaga BOOLEAN NOT NULL DEFAULT false,
    exigir_observacao BOOLEAN NOT NULL DEFAULT true,
    pix_tipo TEXT,
    pix_chave TEXT,
    proximo_numero_ticket INT NOT NULL DEFAULT 1,
    empresa_id INT REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_configuracao_empresa ON public.configuracao(empresa_id);

-- 2. TICKETS
CREATE TABLE IF NOT EXISTS public.tickets (
    numero INT PRIMARY KEY,
    placa TEXT NOT NULL,
    entrada TIMESTAMPTZ NOT NULL DEFAULT now(),
    saida TIMESTAMPTZ,
    valor NUMERIC,
    vaga INT,
    status TEXT NOT NULL DEFAULT 'ABERTO', -- ABERTO | FECHADO
    tipo_veiculo TEXT NOT NULL DEFAULT 'Carro',
    observacoes TEXT,
    forma_pagamento TEXT,
    empresa_id INT REFERENCES public.empresas(id)
);
CREATE INDEX IF NOT EXISTS idx_tickets_placa ON public.tickets(placa);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON public.tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_empresa ON public.tickets(empresa_id);

-- 3. USUARIOS
CREATE TABLE IF NOT EXISTS public.usuarios (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    perfil VARCHAR(50) NOT NULL DEFAULT 'operador',
    ativo BOOLEAN DEFAULT TRUE,
    senha TEXT DEFAULT '',
    trocar_senha_no_proximo_acesso BOOLEAN DEFAULT FALSE,
    empresa_id INTEGER REFERENCES public.empresas(id),
    master BOOLEAN DEFAULT FALSE,
    data_cadastro TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON public.usuarios(email);
CREATE INDEX IF NOT EXISTS idx_usuarios_empresa ON public.usuarios(empresa_id);

-- 4. CLIENTES
CREATE TABLE IF NOT EXISTS public.clientes (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    telefone VARCHAR(30),
    placa VARCHAR(20),
    categoria VARCHAR(50) DEFAULT 'carro_pequeno',
    data_inicio DATE,
    data_fim DATE,
    ativo BOOLEAN DEFAULT TRUE,
    empresa_id INTEGER REFERENCES public.empresas(id),
    data_cadastro TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_clientes_placa ON public.clientes(placa);
CREATE INDEX IF NOT EXISTS idx_clientes_empresa ON public.clientes(empresa_id);
