-- ============================================================
-- Tabela de Permissoes (Funcoes e permissoes)
-- Permite definir dinamicamente o que cada perfil pode fazer
-- em cada modulo do sistema (ver, criar, editar, excluir, etc.)
-- ============================================================

create table if not exists public.permissoes (
    id bigint generated by default as identity primary key,
    perfil text not null,          -- admin | supervisor | operador
    modulo text not null,          -- ex.: caixa, pagamentos, usuarios...
    acao text not null,            -- ex.: ver, criar, editar, excluir...
    criado_em timestamptz default now(),
    unique (perfil, modulo, acao)
);

-- Indice para consultas por perfil
create index if not exists idx_permissoes_perfil on public.permissoes (perfil);
create index if not exists idx_permissoes_modulo on public.permissoes (modulo);

-- ============================================================
-- Permissoes padrao (seed) - podem ser ajustadas pela interface
-- ============================================================

-- OPERADOR
insert into public.permissoes (perfil, modulo, acao) values
    ('operador', 'caixa', 'ver'),
    ('operador', 'caixa', 'criar'),
    ('operador', 'caixa', 'fechar_caixa'),
    ('operador', 'pagamentos', 'ver'),
    ('operador', 'pagamentos', 'criar'),
    ('operador', 'pagamentos', 'cancelar'),
    ('operador', 'formas_pagamento', 'ver'),
    ('operador', 'tabela_precos', 'ver'),
    ('operador', 'descontos', 'ver'),
    ('operador', 'cortesias', 'ver'),
    ('operador', 'cortesias', 'criar'),
    ('operador', 'mensalistas', 'ver'),
    ('operador', 'mensalistas', 'criar'),
    ('operador', 'mensalistas', 'editar'),
    ('operador', 'convenios', 'ver'),
    ('operador', 'contas_receber', 'ver'),
    ('operador', 'estornos', 'ver'),
    ('operador', 'auditoria', 'ver'),
    ('operador', 'dashboard_financeiro', 'ver'),
    ('operador', 'relatorios', 'ver'),
    ('operador', 'usuarios', 'ver')
on conflict (perfil, modulo, acao) do nothing;

-- SUPERVISOR
insert into public.permissoes (perfil, modulo, acao) values
    ('supervisor', 'caixa', 'ver'),
    ('supervisor', 'caixa', 'criar'),
    ('supervisor', 'caixa', 'editar'),
    ('supervisor', 'caixa', 'fechar_caixa'),
    ('supervisor', 'pagamentos', 'ver'),
    ('supervisor', 'pagamentos', 'criar'),
    ('supervisor', 'pagamentos', 'editar'),
    ('supervisor', 'pagamentos', 'cancelar'),
    ('supervisor', 'pagamentos', 'estornar'),
    ('supervisor', 'formas_pagamento', 'ver'),
    ('supervisor', 'formas_pagamento', 'criar'),
    ('supervisor', 'formas_pagamento', 'editar'),
    ('supervisor', 'tabela_precos', 'ver'),
    ('supervisor', 'tabela_precos', 'editar'),
    ('supervisor', 'descontos', 'ver'),
    ('supervisor', 'descontos', 'criar'),
    ('supervisor', 'descontos', 'editar'),
    ('supervisor', 'descontos', 'autorizar'),
    ('supervisor', 'cortesias', 'ver'),
    ('supervisor', 'cortesias', 'criar'),
    ('supervisor', 'cortesias', 'editar'),
    ('supervisor', 'cortesias', 'autorizar'),
    ('supervisor', 'mensalistas', 'ver'),
    ('supervisor', 'mensalistas', 'criar'),
    ('supervisor', 'mensalistas', 'editar'),
    ('supervisor', 'mensalistas', 'excluir'),
    ('supervisor', 'convenios', 'ver'),
    ('supervisor', 'convenios', 'criar'),
    ('supervisor', 'convenios', 'editar'),
    ('supervisor', 'convenios', 'excluir'),
    ('supervisor', 'contas_receber', 'ver'),
    ('supervisor', 'contas_receber', 'criar'),
    ('supervisor', 'contas_receber', 'editar'),
    ('supervisor', 'contas_receber', 'excluir'),
    ('supervisor', 'estornos', 'ver'),
    ('supervisor', 'estornos', 'criar'),
    ('supervisor', 'estornos', 'estornar'),
    ('supervisor', 'auditoria', 'ver'),
    ('supervisor', 'dashboard_financeiro', 'ver'),
    ('supervisor', 'relatorios', 'ver'),
    ('supervisor', 'usuarios', 'ver'),
    ('supervisor', 'usuarios', 'criar'),
    ('supervisor', 'usuarios', 'editar')
on conflict (perfil, modulo, acao) do nothing;
