-- ============================================================
-- MODULO FINANCEIRO PROFISSIONAL - Estaciona Parking
-- Execute este script no SQL Editor do Supabase
-- ============================================================

-- ============================================================
-- 1. CAIXAS
-- ============================================================
create table if not exists public.caixas (
    id bigint generated by default as identity primary key,
    operador text not null,
    data_abertura timestamptz not null default now(),
    valor_inicial numeric not null default 0,
    data_fechamento timestamptz,
    valor_esperado numeric not null default 0,
    valor_contado numeric not null default 0,
    diferenca numeric not null default 0,
    status text not null default 'aberto',        -- aberto | fechado
    observacoes text,
    criado_em timestamptz not null default now(),
    alterado_em timestamptz not null default now(),
    usuario text,
    ip text
);
create index if not exists idx_caixas_status on public.caixas (status);
create index if not exists idx_caixas_data on public.caixas (data_abertura);

-- ============================================================
-- 2. MOVIMENTACOES DE CAIXA
-- ============================================================
create table if not exists public.movimentacoes_caixa (
    id bigint generated by default as identity primary key,
    caixa_id bigint not null references public.caixas(id),
    tipo text not null,                          -- entrada | saida | sangria | suprimento
    descricao text,
    valor numeric not null default 0,
    forma_pagamento text,
    data timestamptz not null default now(),
    usuario text,
    criado_em timestamptz not null default now()
);
create index if not exists idx_mov_caixa on public.movimentacoes_caixa (caixa_id);
create index if not exists idx_mov_caixa_data on public.movimentacoes_caixa (data);

-- ============================================================
-- 3. PAGAMENTOS
-- ============================================================
create table if not exists public.pagamentos (
    id bigint generated by default as identity primary key,
    ticket_numero int,
    valor numeric not null default 0,
    forma_pagamento text not null,
    data timestamptz not null default now(),
    operador text,
    caixa_id bigint references public.caixas(id),
    status text not null default 'ativo',        -- ativo | cancelado | estornado
    motivo_cancelamento text,
    autorizador text,
    criado_em timestamptz not null default now(),
    alterado_em timestamptz not null default now()
);
create index if not exists idx_pagamentos_ticket on public.pagamentos (ticket_numero);
create index if not exists idx_pagamentos_data on public.pagamentos (data);
create index if not exists idx_pagamentos_status on public.pagamentos (status);

-- ============================================================
-- 4. FORMAS DE PAGAMENTO
-- ============================================================
create table if not exists public.formas_pagamento (
    id bigint generated by default as identity primary key,
    nome text not null,
    codigo text not null unique,
    ativo boolean not null default true,
    criado_em timestamptz not null default now()
);

-- ============================================================
-- 5. TABELA DE PRECOS
-- ============================================================
create table if not exists public.tabela_precos (
    id bigint generated by default as identity primary key,
    primeira_hora numeric not null default 0,
    hora_adicional numeric not null default 0,
    diaria numeric not null default 0,
    mensal numeric not null default 0,
    valor_minuto numeric not null default 0,
    valor_maximo_diario numeric not null default 0,
    tolerancia_minutos int not null default 0,
    valor_noturno numeric not null default 0,
    fim_semana numeric not null default 0,
    feriados numeric not null default 0,
    ativo boolean not null default true,
    criado_em timestamptz not null default now(),
    alterado_em timestamptz not null default now()
);

-- ============================================================
-- 6. DESCONTOS
-- ============================================================
create table if not exists public.descontos (
    id bigint generated by default as identity primary key,
    nome text not null,
    tipo text not null,                          -- percentual | fixo
    valor numeric not null default 0,
    motivo text,
    necessita_autorizacao boolean not null default false,
    ativo boolean not null default true,
    criado_em timestamptz not null default now()
);

-- ============================================================
-- 7. CORTESIAS
-- ============================================================
create table if not exists public.cortesias (
    id bigint generated by default as identity primary key,
    motivo text not null,
    usuario text,
    autorizador text,
    data timestamptz not null default now(),
    ticket_numero int,
    status text not null default 'ativo',        -- ativo | cancelado
    criado_em timestamptz not null default now()
);

-- ============================================================
-- 8. MENSALISTAS
-- ============================================================
create table if not exists public.mensalistas (
    id bigint generated by default as identity primary key,
    cliente_id int,
    nome text not null,
    cpf_cnpj text,
    telefone text,
    email text,
    valor_mensal numeric not null default 0,
    dia_vencimento int not null default 5,
    status text not null default 'ativo',        -- ativo | bloqueado | inativo
    criado_em timestamptz not null default now(),
    alterado_em timestamptz not null default now()
);
create index if not exists idx_mensalistas_status on public.mensalistas (status);

-- ============================================================
-- 9. MENSALIDADES
-- ============================================================
create table if not exists public.mensalidades (
    id bigint generated by default as identity primary key,
    mensalista_id bigint not null references public.mensalistas(id),
    competencia text not null,                   -- 'MM/AAAA'
    valor numeric not null default 0,
    data_pagamento timestamptz,
    forma_pagamento text,
    status text not null default 'pendente',     -- pendente | pago | atrasado | cancelado
    criado_em timestamptz not null default now()
);
create index if not exists idx_mensalidades_mensalista on public.mensalidades (mensalista_id);

-- ============================================================
-- 10. CONVENIOS
-- ============================================================
create table if not exists public.convenios (
    id bigint generated by default as identity primary key,
    nome text not null,
    cnpj text,
    contato text,
    ativo boolean not null default true,
    criado_em timestamptz not null default now()
);

-- ============================================================
-- 11. CONTAS A RECEBER
-- ============================================================
create table if not exists public.contas_receber (
    id bigint generated by default as identity primary key,
    convenio_id bigint references public.convenios(id),
    descricao text,
    valor numeric not null default 0,
    vencimento timestamptz,
    status text not null default 'aberta',       -- aberta | paga | cancelada
    data_pagamento timestamptz,
    forma_pagamento text,
    criado_em timestamptz not null default now()
);
create index if not exists idx_contas_receber_status on public.contas_receber (status);

-- ============================================================
-- 12. SANGRIA E SUPRIMENTO
-- ============================================================
create table if not exists public.sangrias (
    id bigint generated by default as identity primary key,
    caixa_id bigint references public.caixas(id),
    valor numeric not null default 0,
    motivo text,
    operador text,
    data timestamptz not null default now(),
    criado_em timestamptz not null default now()
);

create table if not exists public.suprimentos (
    id bigint generated by default as identity primary key,
    caixa_id bigint references public.caixas(id),
    valor numeric not null default 0,
    motivo text,
    operador text,
    data timestamptz not null default now(),
    criado_em timestamptz not null default now()
);

-- ============================================================
-- 13. ESTORNOS
-- ============================================================
create table if not exists public.estornos (
    id bigint generated by default as identity primary key,
    pagamento_id bigint references public.pagamentos(id),
    valor numeric not null default 0,
    motivo text,
    operador text,
    forma_pagamento text,
    data timestamptz not null default now(),
    autorizador text,
    criado_em timestamptz not null default now()
);

-- ============================================================
-- 14. AUDITORIA
-- ============================================================
create table if not exists public.auditoria (
    id bigint generated by default as identity primary key,
    tabela text not null,
    registro_id bigint,
    campo text,
    valor_antigo text,
    valor_novo text,
    usuario text,
    data timestamptz not null default now(),
    ip text
);
create index if not exists idx_auditoria_tabela on public.auditoria (tabela);
create index if not exists idx_auditoria_data on public.auditoria (data);

-- ============================================================
-- 15. LOGS DE ACESSO
-- ============================================================
create table if not exists public.logs_acesso (
    id bigint generated by default as identity primary key,
    usuario text,
    acao text,
    modulo text,
    data timestamptz not null default now(),
    ip text
);
create index if not exists idx_logs_acesso_data on public.logs_acesso (data);

-- ============================================================
-- PERMISSOES (RLS) - desabilitado por padrao; ajuste conforme politica
-- ============================================================
alter table public.caixas enable row level security;
create policy "caixas_all" on public.caixas for all using (true) with check (true);
alter table public.movimentacoes_caixa enable row level security;
create policy "mov_caixa_all" on public.movimentacoes_caixa for all using (true) with check (true);
alter table public.pagamentos enable row level security;
create policy "pagamentos_all" on public.pagamentos for all using (true) with check (true);
alter table public.formas_pagamento enable row level security;
create policy "formas_all" on public.formas_pagamento for all using (true) with check (true);
alter table public.tabela_precos enable row level security;
create policy "tabela_precos_all" on public.tabela_precos for all using (true) with check (true);
alter table public.descontos enable row level security;
create policy "descontos_all" on public.descontos for all using (true) with check (true);
alter table public.cortesias enable row level security;
create policy "cortesias_all" on public.cortesias for all using (true) with check (true);
alter table public.mensalistas enable row level security;
create policy "mensalistas_all" on public.mensalistas for all using (true) with check (true);
alter table public.mensalidades enable row level security;
create policy "mensalidades_all" on public.mensalidades for all using (true) with check (true);
alter table public.convenios enable row level security;
create policy "convenios_all" on public.convenios for all using (true) with check (true);
alter table public.contas_receber enable row level security;
create policy "contas_receber_all" on public.contas_receber for all using (true) with check (true);
alter table public.sangrias enable row level security;
create policy "sangrias_all" on public.sangrias for all using (true) with check (true);
alter table public.suprimentos enable row level security;
create policy "suprimentos_all" on public.suprimentos for all using (true) with check (true);
alter table public.estornos enable row level security;
create policy "estornos_all" on public.estornos for all using (true) with check (true);
alter table public.auditoria enable row level security;
create policy "auditoria_all" on public.auditoria for all using (true) with check (true);
alter table public.logs_acesso enable row level security;
create policy "logs_acesso_all" on public.logs_acesso for all using (true) with check (true);
