-- ============================================================
-- Tabela: financeiro (modulo financeiro do estacionamento)
-- Execute este script no SQL Editor do Supabase
-- ============================================================

create table if not exists public.financeiro (
    id bigint generated by default as identity primary key,
    tipo text not null,                          -- 'entrada' (receita) ou 'saida' (despesa)
    descricao text not null,                     -- descricao do lancamento
    valor numeric not null,                      -- valor (positivo)
    forma_pagamento text not null,               -- dinheiro, pix, cartao_credito, cartao_debito
    data timestamptz not null,                   -- data/hora do lancamento
    origem text not null default 'manual',       -- 'ticket' (automatico) ou 'manual'
    ticket_numero int                            -- numero do ticket vinculado (quando origem=ticket)
);

-- Indice para consultas por periodo (data)
create index if not exists idx_financeiro_data on public.financeiro (data);

-- Permissoes (RLS desabilitado por padrao; ajuste conforme sua politica)
alter table public.financeiro enable row level security;
create policy "financeiro_all" on public.financeiro
    for all
    using (true)
    with check (true);
