-- ==============================================================================
-- SISTEMA DE GESTÃO DE ESTACIONAMENTO (PARKING SYSTEM)
-- SCRIPT MESTRE DE PREPARAÇÃO COMPLETA DO SUPABASE / POSTGRESQL
-- ==============================================================================
-- Este script é idempotente: pode ser executado em bancos novos ou já existentes.
-- Execução: Cole o conteúdo no SQL Editor do Supabase e clique em "Run".
-- ==============================================================================

-- ==============================================================================
-- 1. TABELAS DE ACESSO, SEGURANÇA E MULTI-EMPRESA
-- ==============================================================================

-- 1.1 EMPRESAS (Estacionamentos / Multi-CNPJ)
CREATE TABLE IF NOT EXISTS public.empresas (
    id SERIAL PRIMARY KEY,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    razao_social VARCHAR(200) NOT NULL,
    nome_fantasia VARCHAR(200) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(200),
    endereco TEXT,
    cidade VARCHAR(100),
    estado VARCHAR(2),
    cep VARCHAR(10),
    ativo BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    alterado_em TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_empresas_cnpj ON public.empresas(cnpj);
CREATE INDEX IF NOT EXISTS idx_empresas_ativo ON public.empresas(ativo);

-- Migra tabelas que ja existiam antes do suporte multiempresa. O bloco fica
-- antes dos CREATE INDEX para que esquemas antigos nao falhem em empresa_id.
DO $$
DECLARE
    tbl text;
    tabelas_empresa text[] := ARRAY[
        'usuarios', 'configuracao', 'tickets', 'clientes', 'tipos_veiculo',
        'caixas', 'movimentacoes_caixa', 'formas_pagamento', 'tabela_precos',
        'pagamentos', 'descontos', 'cortesias', 'mensalistas', 'mensalidades',
        'convenios', 'contas_receber', 'sangrias', 'suprimentos', 'estornos',
        'financeiro', 'nfse', 'lista_negra', 'reservas', 'ocorrencias'
    ];
BEGIN
    FOREACH tbl IN ARRAY tabelas_empresa LOOP
        IF to_regclass(format('public.%I', tbl)) IS NOT NULL THEN
            EXECUTE format(
                'ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS empresa_id INTEGER REFERENCES public.empresas(id)',
                tbl
            );
        END IF;
    END LOOP;

    IF to_regclass('public.usuarios') IS NOT NULL THEN
        EXECUTE
            'ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS master BOOLEAN NOT NULL DEFAULT FALSE';
    END IF;

    IF to_regclass('public.mensalistas') IS NOT NULL THEN
        EXECUTE
            'ALTER TABLE public.mensalistas ADD COLUMN IF NOT EXISTS placa TEXT';
        EXECUTE
            'ALTER TABLE public.mensalistas ADD COLUMN IF NOT EXISTS tipo_veiculo TEXT DEFAULT ''Carro''';
    END IF;
END $$;

-- 1.2 PERFIS DE ACESSO
CREATE TABLE IF NOT EXISTS public.perfis (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    alterado_em TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_perfis_codigo ON public.perfis(codigo);
CREATE INDEX IF NOT EXISTS idx_perfis_ativo ON public.perfis(ativo);

-- 1.3 USUÁRIOS DO SISTEMA
CREATE TABLE IF NOT EXISTS public.usuarios (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    perfil VARCHAR(50) NOT NULL DEFAULT 'operador',
    ativo BOOLEAN DEFAULT TRUE,
    senha TEXT DEFAULT '',
    trocar_senha_no_proximo_acesso BOOLEAN DEFAULT FALSE,
    empresa_id INTEGER REFERENCES public.empresas(id),
    master BOOLEAN DEFAULT FALSE,
    data_cadastro TIMESTAMPTZ DEFAULT NOW()
);

-- Bancos antigos podem ter usuarios.id como NOT NULL sem sequence/default.
-- Garante geração automatica e sincroniza o proximo valor com os IDs existentes.
DO $$
DECLARE
    seq_name text;
BEGIN
    seq_name := pg_get_serial_sequence('public.usuarios', 'id');

    IF seq_name IS NULL THEN
        CREATE SEQUENCE IF NOT EXISTS public.usuarios_id_seq;
        ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;
        ALTER TABLE public.usuarios
            ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);
        seq_name := 'public.usuarios_id_seq';
    END IF;

    PERFORM setval(
        seq_name::regclass,
        COALESCE((SELECT MAX(id) FROM public.usuarios), 1),
        EXISTS (SELECT 1 FROM public.usuarios)
    );
END $$;

CREATE INDEX IF NOT EXISTS idx_usuarios_email ON public.usuarios(email);
CREATE INDEX IF NOT EXISTS idx_usuarios_empresa ON public.usuarios(empresa_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_perfil ON public.usuarios(perfil);

-- 1.4 MATRIZ DINÂMICA DE PERMISSÕES
CREATE TABLE IF NOT EXISTS public.permissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil TEXT NOT NULL,
    modulo TEXT NOT NULL,
    acao TEXT NOT NULL,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (perfil, modulo, acao)
);
CREATE INDEX IF NOT EXISTS idx_permissoes_perfil ON public.permissoes(perfil);
CREATE INDEX IF NOT EXISTS idx_permissoes_modulo ON public.permissoes(modulo);


-- ==============================================================================
-- 2. OPERAÇÃO BASE DO PÁTIO, VEÍCULOS E CLIENTES
-- ==============================================================================

-- 2.1 CONFIGURAÇÃO GERAL
CREATE TABLE IF NOT EXISTS public.configuracao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_estacionamento TEXT NOT NULL DEFAULT 'Estaciona Parking',
    cnpj TEXT,
    telefone TEXT,
    endereco TEXT,
    cidade TEXT,
    estado TEXT,
    cep TEXT,
    total_vagas INT NOT NULL DEFAULT 20,
    vagas_carro INT NOT NULL DEFAULT 0,
    vagas_moto INT NOT NULL DEFAULT 0,
    vagas_carro_grande INT NOT NULL DEFAULT 0,
    vagas_caminhonete INT NOT NULL DEFAULT 0,
    valor_primeira_hora NUMERIC NOT NULL DEFAULT 5.0,
    valor_hora_adicional NUMERIC NOT NULL DEFAULT 3.0,
    valor_mensal NUMERIC NOT NULL DEFAULT 150.0,
    horario_abertura TIME,
    horario_fechamento TIME,
    cabecalho_ticket TEXT,
    rodape_ticket TEXT,
    ticket_exibir_cnpj BOOLEAN NOT NULL DEFAULT TRUE,
    ticket_exibir_contato BOOLEAN NOT NULL DEFAULT TRUE,
    ticket_formato_papel TEXT NOT NULL DEFAULT '80mm',
    ticket_exibir_codigo_barras BOOLEAN NOT NULL DEFAULT TRUE,
    bloquear_sem_vaga BOOLEAN NOT NULL DEFAULT FALSE,
    exigir_observacao BOOLEAN NOT NULL DEFAULT TRUE,
    pix_tipo VARCHAR(20),
    pix_chave VARCHAR(255),
    proximo_numero_ticket INT NOT NULL DEFAULT 1,
    empresa_id INT REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    alterado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_configuracao_empresa ON public.configuracao(empresa_id);

-- 2.2 TICKETS DE ENTRADA/SAÍDA (AVULSOS)
CREATE TABLE IF NOT EXISTS public.tickets (
    numero INT PRIMARY KEY,
    placa TEXT NOT NULL,
    entrada TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    saida TIMESTAMPTZ,
    valor NUMERIC,
    vaga INT,
    status TEXT NOT NULL DEFAULT 'ABERTO', -- ABERTO | FECHADO
    tipo_veiculo TEXT NOT NULL DEFAULT 'Carro',
    observacoes TEXT,
    forma_pagamento TEXT,
    empresa_id INT REFERENCES public.empresas(id)
);
CREATE INDEX IF NOT EXISTS idx_tickets_placa ON public.tickets(placa);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON public.tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_empresa ON public.tickets(empresa_id);
CREATE INDEX IF NOT EXISTS idx_tickets_entrada ON public.tickets(entrada);

-- 2.3 CLIENTES (MENSALISTAS / CONTRATOS BASE)
CREATE TABLE IF NOT EXISTS public.clientes (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    telefone VARCHAR(30),
    placa VARCHAR(20),
    categoria VARCHAR(50) DEFAULT 'carro_pequeno',
    data_inicio DATE,
    data_fim DATE,
    ativo BOOLEAN DEFAULT TRUE,
    empresa_id INTEGER REFERENCES public.empresas(id),
    data_cadastro TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_clientes_placa ON public.clientes(placa);
CREATE INDEX IF NOT EXISTS idx_clientes_empresa ON public.clientes(empresa_id);
CREATE INDEX IF NOT EXISTS idx_clientes_ativo ON public.clientes(ativo);

-- 2.4 TIPOS DE VEÍCULO
CREATE TABLE IF NOT EXISTS public.tipos_veiculo (
    id INTEGER PRIMARY KEY,
    empresa_id INTEGER REFERENCES public.empresas(id),
    nome TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TEXT,
    primeira_hora NUMERIC NOT NULL DEFAULT 0,
    hora_adicional NUMERIC NOT NULL DEFAULT 0,
    diaria NUMERIC NOT NULL DEFAULT 0,
    valor_minuto NUMERIC NOT NULL DEFAULT 0,
    valor_maximo_diario NUMERIC NOT NULL DEFAULT 0,
    mensal NUMERIC NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_tipos_veiculo_empresa ON public.tipos_veiculo(empresa_id);


-- ==============================================================================
-- 3. MÓDULO FINANCEIRO, CAIXA E PREÇOS
-- ==============================================================================

-- 3.1 CAIXAS OPERACIONAIS
CREATE TABLE IF NOT EXISTS public.caixas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operador TEXT NOT NULL,
    data_abertura TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valor_inicial NUMERIC NOT NULL DEFAULT 0,
    data_fechamento TIMESTAMPTZ,
    valor_esperado NUMERIC NOT NULL DEFAULT 0,
    valor_contado NUMERIC NOT NULL DEFAULT 0,
    diferenca NUMERIC NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'aberto',        -- aberto | fechado
    observacoes TEXT,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    alterado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usuario TEXT,
    ip TEXT
);
CREATE INDEX IF NOT EXISTS idx_caixas_status ON public.caixas(status);
CREATE INDEX IF NOT EXISTS idx_caixas_empresa ON public.caixas(empresa_id);
CREATE INDEX IF NOT EXISTS idx_caixas_data ON public.caixas(data_abertura);

-- 3.2 MOVIMENTAÇÕES DE CAIXA
CREATE TABLE IF NOT EXISTS public.movimentacoes_caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caixa_id BIGINT NOT NULL REFERENCES public.caixas(id),
    tipo TEXT NOT NULL,                          -- entrada | saida | sangria | suprimento
    descricao TEXT,
    valor NUMERIC NOT NULL DEFAULT 0,
    forma_pagamento TEXT,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usuario TEXT,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_mov_caixa ON public.movimentacoes_caixa(caixa_id);
CREATE INDEX IF NOT EXISTS idx_mov_caixa_empresa ON public.movimentacoes_caixa(empresa_id);
CREATE INDEX IF NOT EXISTS idx_mov_caixa_data ON public.movimentacoes_caixa(data);

-- 3.3 FORMAS DE PAGAMENTO
CREATE TABLE IF NOT EXISTS public.formas_pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    codigo TEXT NOT NULL UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_formas_pagamento_empresa ON public.formas_pagamento(empresa_id);

-- 3.4 TABELA DE PREÇOS
CREATE TABLE IF NOT EXISTS public.tabela_precos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primeira_hora NUMERIC NOT NULL DEFAULT 0,
    hora_adicional NUMERIC NOT NULL DEFAULT 0,
    diaria NUMERIC NOT NULL DEFAULT 0,
    mensal NUMERIC NOT NULL DEFAULT 0,
    valor_minuto NUMERIC NOT NULL DEFAULT 0,
    valor_maximo_diario NUMERIC NOT NULL DEFAULT 0,
    tolerancia_minutos INT NOT NULL DEFAULT 0,
    valor_noturno NUMERIC NOT NULL DEFAULT 0,
    fim_semana NUMERIC NOT NULL DEFAULT 0,
    feriados NUMERIC NOT NULL DEFAULT 0,
    fracionamento_minutos INT DEFAULT 60,
    tarifa_minima NUMERIC(10,2) DEFAULT 0,
    meia_estadia_minutos INT DEFAULT 0,
    meia_estadia_valor NUMERIC(10,2) DEFAULT 0,
    valor_ticket_perdido NUMERIC(12,2) DEFAULT 0,
    pernoite_valor NUMERIC(12,2) DEFAULT 0,
    pernoite_a_partir_horas INT DEFAULT 12,
    carro_grande_primeira_hora NUMERIC(10,2) DEFAULT 0,
    carro_grande_hora_adicional NUMERIC(10,2) DEFAULT 0,
    carro_grande_diaria NUMERIC(10,2) DEFAULT 0,
    carro_grande_valor_minuto NUMERIC(10,2) DEFAULT 0,
    carro_grande_valor_maximo_diario NUMERIC(10,2) DEFAULT 0,
    carro_grande_mensal NUMERIC(10,2) DEFAULT 0,
    moto_primeira_hora NUMERIC(10,2) DEFAULT 0,
    moto_hora_adicional NUMERIC(10,2) DEFAULT 0,
    moto_diaria NUMERIC(10,2) DEFAULT 0,
    moto_valor_minuto NUMERIC(10,2) DEFAULT 0,
    moto_valor_maximo_diario NUMERIC(10,2) DEFAULT 0,
    moto_mensal NUMERIC(10,2) DEFAULT 0,
    caminhonete_primeira_hora NUMERIC(10,2) DEFAULT 0,
    caminhonete_hora_adicional NUMERIC(10,2) DEFAULT 0,
    caminhonete_diaria NUMERIC(10,2) DEFAULT 0,
    caminhonete_valor_minuto NUMERIC(10,2) DEFAULT 0,
    caminhonete_valor_maximo_diario NUMERIC(10,2) DEFAULT 0,
    caminhonete_mensal NUMERIC(10,2) DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    alterado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tabela_precos_empresa ON public.tabela_precos(empresa_id);

-- 3.5 PAGAMENTOS EFETUADOS
CREATE TABLE IF NOT EXISTS public.pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_numero INT,
    valor NUMERIC NOT NULL DEFAULT 0,
    forma_pagamento TEXT NOT NULL,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    operador TEXT,
    caixa_id BIGINT REFERENCES public.caixas(id),
    status TEXT NOT NULL DEFAULT 'ativo',        -- ativo | cancelado | estornado
    motivo_cancelamento TEXT,
    autorizador TEXT,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    alterado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pagamentos_ticket ON public.pagamentos(ticket_numero);
CREATE INDEX IF NOT EXISTS idx_pagamentos_empresa ON public.pagamentos(empresa_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_data ON public.pagamentos(data);
CREATE INDEX IF NOT EXISTS idx_pagamentos_status ON public.pagamentos(status);

-- 3.6 DESCONTOS CONCEDIDOS / CADASTRO
CREATE TABLE IF NOT EXISTS public.descontos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL,                          -- percentual | fixo
    valor NUMERIC NOT NULL DEFAULT 0,
    motivo TEXT,
    necessita_autorizacao BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_descontos_empresa ON public.descontos(empresa_id);

-- 3.7 CORTESIAS
CREATE TABLE IF NOT EXISTS public.cortesias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motivo TEXT NOT NULL,
    usuario TEXT,
    autorizador TEXT,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ticket_numero INT,
    status TEXT NOT NULL DEFAULT 'ativo',        -- ativo | cancelado
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cortesias_empresa ON public.cortesias(empresa_id);

-- 3.8 MENSALISTAS
CREATE TABLE IF NOT EXISTS public.mensalistas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INT,
    nome TEXT NOT NULL,
    cpf_cnpj TEXT,
    telefone TEXT,
    email TEXT,
    placa TEXT,
    tipo_veiculo TEXT DEFAULT 'Carro',
    valor_mensal NUMERIC NOT NULL DEFAULT 0,
    dia_vencimento INT NOT NULL DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'ativo',        -- ativo | bloqueado | inativo
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    alterado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_mensalistas_status ON public.mensalistas(status);
CREATE INDEX IF NOT EXISTS idx_mensalistas_placa ON public.mensalistas(placa);
CREATE INDEX IF NOT EXISTS idx_mensalistas_empresa ON public.mensalistas(empresa_id);

-- 3.9 MENSALIDADES (COBRANÇAS / FATURAS)
CREATE TABLE IF NOT EXISTS public.mensalidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensalista_id BIGINT NOT NULL REFERENCES public.mensalistas(id),
    competencia TEXT NOT NULL,                   -- 'MM/AAAA'
    valor NUMERIC NOT NULL DEFAULT 0,
    data_pagamento TIMESTAMPTZ,
    forma_pagamento TEXT,
    status TEXT NOT NULL DEFAULT 'pendente',     -- pendente | pago | atrasado | cancelado
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_mensalidades_mensalista ON public.mensalidades(mensalista_id);
CREATE INDEX IF NOT EXISTS idx_mensalidades_empresa ON public.mensalidades(empresa_id);

-- 3.10 CONVÊNIOS (EMPRESAS PARCEIRAS)
CREATE TABLE IF NOT EXISTS public.convenios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cnpj TEXT,
    contato TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_convenios_empresa ON public.convenios(empresa_id);

-- 3.11 CONTAS A RECEBER (FATURAMENTO DE CONVÊNIOS)
CREATE TABLE IF NOT EXISTS public.contas_receber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    convenio_id BIGINT REFERENCES public.convenios(id),
    descricao TEXT,
    valor NUMERIC NOT NULL DEFAULT 0,
    vencimento TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'aberta',       -- aberta | paga | cancelada
    data_pagamento TIMESTAMPTZ,
    forma_pagamento TEXT,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_contas_receber_status ON public.contas_receber(status);
CREATE INDEX IF NOT EXISTS idx_contas_receber_empresa ON public.contas_receber(empresa_id);

-- 3.12 SANGRIAS E SUPRIMENTOS (TABELAS DEDICADAS DE AUDITORIA)
CREATE TABLE IF NOT EXISTS public.sangrias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caixa_id BIGINT REFERENCES public.caixas(id),
    valor NUMERIC NOT NULL DEFAULT 0,
    motivo TEXT,
    operador TEXT,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sangrias_empresa ON public.sangrias(empresa_id);

CREATE TABLE IF NOT EXISTS public.suprimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caixa_id BIGINT REFERENCES public.caixas(id),
    valor NUMERIC NOT NULL DEFAULT 0,
    motivo TEXT,
    operador TEXT,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_suprimentos_empresa ON public.suprimentos(empresa_id);

-- 3.13 ESTORNOS
CREATE TABLE IF NOT EXISTS public.estornos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pagamento_id BIGINT REFERENCES public.pagamentos(id),
    valor NUMERIC NOT NULL DEFAULT 0,
    motivo TEXT,
    operador TEXT,
    forma_pagamento TEXT,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    autorizador TEXT,
    empresa_id INTEGER REFERENCES public.empresas(id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_estornos_empresa ON public.estornos(empresa_id);

-- 3.14 LANÇAMENTOS FINANCEIROS GERAIS (DRE / FLUXO DE CAIXA)
CREATE TABLE IF NOT EXISTS public.financeiro (
    id SERIAL PRIMARY KEY,
    tipo TEXT NOT NULL,                          -- entrada | saida
    descricao TEXT NOT NULL,
    valor NUMERIC NOT NULL DEFAULT 0,
    forma_pagamento TEXT DEFAULT 'dinheiro',
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    origem TEXT DEFAULT 'manual',                -- ticket | manual
    ticket_numero INT,
    empresa_id INTEGER REFERENCES public.empresas(id)
);
CREATE INDEX IF NOT EXISTS idx_financeiro_data ON public.financeiro(data);
CREATE INDEX IF NOT EXISTS idx_financeiro_empresa ON public.financeiro(empresa_id);
CREATE INDEX IF NOT EXISTS idx_financeiro_tipo ON public.financeiro(tipo);


-- ==============================================================================
-- 4. MÓDULOS AVANÇADOS (NFSE, LISTA NEGRA, RESERVAS, OCORRÊNCIAS, AUDITORIA)
-- ==============================================================================

-- 4.1 AUDITORIA
CREATE TABLE IF NOT EXISTS public.auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela TEXT NOT NULL,
    registro_id BIGINT,
    campo TEXT,
    valor_antigo TEXT,
    valor_novo TEXT,
    usuario TEXT,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip TEXT
);
CREATE INDEX IF NOT EXISTS idx_auditoria_tabela ON public.auditoria(tabela);
CREATE INDEX IF NOT EXISTS idx_auditoria_data ON public.auditoria(data);

-- 4.2 LOGS DE ACESSO
CREATE TABLE IF NOT EXISTS public.logs_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT,
    acao TEXT,
    modulo TEXT,
    data TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip TEXT
);
CREATE INDEX IF NOT EXISTS idx_logs_acesso_data ON public.logs_acesso(data);

-- 4.3 NFSe (NOTAS FISCAIS DE SERVIÇO)
CREATE TABLE IF NOT EXISTS public.nfse (
    id BIGINT PRIMARY KEY,
    numero BIGINT NOT NULL,
    ticket_numero BIGINT,
    placa TEXT,
    valor NUMERIC(12,2) NOT NULL DEFAULT 0,
    cpf_cnpj TEXT,
    razao_social TEXT,
    servico TEXT,
    data TEXT,
    usuario TEXT,
    status TEXT NOT NULL DEFAULT 'emitida',
    empresa_id BIGINT REFERENCES public.empresas(id),
    criado_em TEXT
);
CREATE INDEX IF NOT EXISTS idx_nfse_empresa ON public.nfse(empresa_id);
CREATE INDEX IF NOT EXISTS idx_nfse_ticket ON public.nfse(ticket_numero);

-- 4.4 LISTA NEGRA (BLOQUEIO DE VEÍCULOS)
CREATE TABLE IF NOT EXISTS public.lista_negra (
    id BIGINT PRIMARY KEY,
    placa TEXT NOT NULL,
    motivo TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    usuario TEXT,
    data TEXT,
    empresa_id BIGINT REFERENCES public.empresas(id),
    criado_em TEXT
);
CREATE INDEX IF NOT EXISTS idx_lista_negra_empresa ON public.lista_negra(empresa_id);
CREATE INDEX IF NOT EXISTS idx_lista_negra_placa ON public.lista_negra(placa);

-- 4.5 RESERVAS DE VAGAS
CREATE TABLE IF NOT EXISTS public.reservas (
    id BIGINT PRIMARY KEY,
    cliente TEXT,
    telefone TEXT,
    placa TEXT,
    tipo_veiculo TEXT,
    vaga INTEGER,
    data_inicio TEXT,
    data_fim TEXT,
    valor NUMERIC(12,2) NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'ativa',
    observacao TEXT,
    usuario TEXT,
    empresa_id BIGINT REFERENCES public.empresas(id),
    criado_em TEXT,
    alterado_em TEXT
);
CREATE INDEX IF NOT EXISTS idx_reservas_empresa ON public.reservas(empresa_id);
CREATE INDEX IF NOT EXISTS idx_reservas_status ON public.reservas(status);

-- 4.6 OCORRÊNCIAS / TERMO DE AVARIAS
CREATE TABLE IF NOT EXISTS public.ocorrencias (
    id BIGINT PRIMARY KEY,
    tipo TEXT NOT NULL DEFAULT 'avaria',
    placa TEXT,
    ticket_numero BIGINT,
    descricao TEXT,
    status TEXT NOT NULL DEFAULT 'aberta',
    usuario TEXT,
    autorizador TEXT,
    data TEXT,
    empresa_id BIGINT REFERENCES public.empresas(id),
    criado_em TEXT,
    alterado_em TEXT
);
CREATE INDEX IF NOT EXISTS idx_ocorrencias_empresa ON public.ocorrencias(empresa_id);
CREATE INDEX IF NOT EXISTS idx_ocorrencias_placa ON public.ocorrencias(placa);


-- ==============================================================================
-- 5. ATUALIZAÇÃO RETROATIVA DE COLUNAS (MIGRAÇÕES PENDENTES)
-- ==============================================================================

-- Colunas da tabela configuracao
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS cnpj VARCHAR(20);
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS telefone VARCHAR(20);
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS endereco TEXT;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS cidade VARCHAR(100);
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS estado VARCHAR(2);
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS cep VARCHAR(10);
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS horario_abertura TIME;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS horario_fechamento TIME;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS cabecalho_ticket TEXT;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS rodape_ticket TEXT;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS bloquear_sem_vaga BOOLEAN DEFAULT FALSE;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS exigir_observacao BOOLEAN DEFAULT TRUE;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS vagas_carro INTEGER DEFAULT 0;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS vagas_moto INTEGER DEFAULT 0;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS vagas_carro_grande INTEGER DEFAULT 0;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS vagas_caminhonete INTEGER DEFAULT 0;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS pix_tipo VARCHAR(20);
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS pix_chave VARCHAR(255);
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS ticket_exibir_cnpj BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS ticket_exibir_contato BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS ticket_formato_papel TEXT NOT NULL DEFAULT '80mm';
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS ticket_exibir_codigo_barras BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.configuracao ADD COLUMN IF NOT EXISTS empresa_id INTEGER REFERENCES public.empresas(id);

-- Colunas da tabela tickets
ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS forma_pagamento TEXT;
ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS empresa_id INTEGER REFERENCES public.empresas(id);

-- Colunas da tabela clientes
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS empresa_id INTEGER REFERENCES public.empresas(id);

-- Colunas da tabela mensalistas
ALTER TABLE public.mensalistas ADD COLUMN IF NOT EXISTS placa TEXT;
ALTER TABLE public.mensalistas ADD COLUMN IF NOT EXISTS tipo_veiculo TEXT DEFAULT 'Carro';
ALTER TABLE public.mensalistas ADD COLUMN IF NOT EXISTS empresa_id INTEGER REFERENCES public.empresas(id);

-- Colunas da tabela movimentacoes_caixa
ALTER TABLE public.movimentacoes_caixa ADD COLUMN IF NOT EXISTS empresa_id INTEGER REFERENCES public.empresas(id);

-- Colunas da tabela tabela_precos
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS valor_ticket_perdido NUMERIC(12,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS pernoite_valor NUMERIC(12,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS pernoite_a_partir_horas INT DEFAULT 12;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS fracionamento_minutos INT DEFAULT 60;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS tarifa_minima NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS meia_estadia_minutos INT DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS meia_estadia_valor NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS carro_grande_primeira_hora NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS carro_grande_hora_adicional NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS carro_grande_diaria NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS carro_grande_valor_minuto NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS carro_grande_valor_maximo_diario NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS carro_grande_mensal NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS moto_primeira_hora NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS moto_hora_adicional NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS moto_diaria NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS moto_valor_minuto NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS moto_valor_maximo_diario NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS moto_mensal NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS caminhonete_primeira_hora NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS caminhonete_hora_adicional NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS caminhonete_diaria NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS caminhonete_valor_minuto NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS caminhonete_valor_maximo_diario NUMERIC(10,2) DEFAULT 0;
ALTER TABLE public.tabela_precos ADD COLUMN IF NOT EXISTS caminhonete_mensal NUMERIC(10,2) DEFAULT 0;


-- ==============================================================================
-- 6. POLÍTICAS DE ACESSO E RLS (ROW LEVEL SECURITY)
-- ==============================================================================
-- O sistema utiliza autenticação própria e controle de sessão gerenciado pelo Flask.
-- O acesso ao banco deve ocorrer somente pelo backend usando a chave service_role.
-- Nao exponha essa chave no navegador nem conceda acesso direto a anon/authenticated.

DO $$
DECLARE
    tbl text;
    tabelas_sistema text[] := ARRAY[
        'empresas', 'perfis', 'usuarios', 'permissoes', 'configuracao', 'tickets',
        'clientes', 'tipos_veiculo', 'caixas', 'movimentacoes_caixa', 'formas_pagamento',
        'tabela_precos', 'pagamentos', 'descontos', 'cortesias', 'mensalistas',
        'mensalidades', 'convenios', 'contas_receber', 'sangrias', 'suprimentos',
        'estornos', 'financeiro', 'auditoria', 'logs_acesso', 'nfse', 'lista_negra',
        'reservas', 'ocorrencias'
    ];
BEGIN
    FOREACH tbl IN ARRAY tabelas_sistema LOOP
        EXECUTE format('ALTER TABLE IF EXISTS public.%I ENABLE ROW LEVEL SECURITY;', tbl);
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated;', tbl);
        EXECUTE format('GRANT ALL ON TABLE public.%I TO service_role;', tbl);
    END LOOP;
END $$;

-- Permissões em sequences para inserções automáticas
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;


-- ==============================================================================
-- 7. DADOS INICIAIS (SEEDS OBRIGATÓRIOS E IDEMPOTENTES)
-- ==============================================================================

-- Sincroniza sequences antes dos inserts seed. Em bancos antigos a sequence
-- pode estar atras da tabela, causando duplicate key mesmo sem IDs explicitos.
SELECT setval(
    pg_get_serial_sequence('public.empresas', 'id'),
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM public.empresas;
SELECT setval(
    pg_get_serial_sequence('public.perfis', 'id'),
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM public.perfis;
SELECT setval(
    pg_get_serial_sequence('public.usuarios', 'id'),
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM public.usuarios;
SELECT setval(
    pg_get_serial_sequence('public.clientes', 'id'),
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM public.clientes;
SELECT setval(
    pg_get_serial_sequence('public.financeiro', 'id'),
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM public.financeiro;

-- 7.1 Empresas Base
INSERT INTO public.empresas (cnpj, razao_social, nome_fantasia, ativo)
VALUES 
    ('00.000.000/0001-00', 'Empresa Padrao', 'Estacionamento Padrao', TRUE),
    ('11.222.333/0001-44', 'Centro Park Ltda', 'Centro Park', TRUE)
ON CONFLICT (cnpj) DO UPDATE SET
    nome_fantasia = EXCLUDED.nome_fantasia,
    razao_social = EXCLUDED.razao_social,
    ativo = TRUE;

-- 7.2 Perfis de Acesso
INSERT INTO public.perfis (codigo, nome, descricao, ativo)
VALUES
    ('admin', 'Administrador', 'Acesso total a todos os modulos e acoes do sistema.', TRUE),
    ('supervisor', 'Supervisor', 'Gestao e autorizacoes, sem acesso total.', TRUE),
    ('operador', 'Operador', 'Operacao diaria do estacionamento.', TRUE)
ON CONFLICT (codigo) DO UPDATE SET
    nome = EXCLUDED.nome,
    descricao = EXCLUDED.descricao,
    ativo = TRUE;

-- 7.3 Usuários Iniciais (com hash seguro PBKDF2 para 'admin123')
INSERT INTO public.usuarios (nome, email, perfil, ativo, senha, master, empresa_id)
VALUES
    ('Administrador', 'admin@teste.com', 'admin', TRUE, 'pbkdf2:salthash12345678:87a4a9b2f9de5fe032cdd608696e47433166780f73d9cf56cc11e92c9ca2449b', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00')),
    ('Master Jotazyn', 'jotazyn@outlook.com', 'admin', TRUE, 'pbkdf2:salthash12345678:87a4a9b2f9de5fe032cdd608696e47433166780f73d9cf56cc11e92c9ca2449b', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00')),
    ('Operador Teste', 'operador@teste.com', 'operador', TRUE, 'pbkdf2:salthash12345678:87a4a9b2f9de5fe032cdd608696e47433166780f73d9cf56cc11e92c9ca2449b', FALSE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00'))
ON CONFLICT (email) DO UPDATE SET
    perfil = EXCLUDED.perfil,
    ativo = TRUE,
    master = EXCLUDED.master;

-- 7.4 Configuração Padrão do Estacionamento
INSERT INTO public.configuracao (
    empresa_id, nome_estacionamento, total_vagas,
    vagas_carro, vagas_moto, vagas_carro_grande, vagas_caminhonete,
    valor_primeira_hora, valor_hora_adicional, valor_mensal,
    ticket_formato_papel, ticket_exibir_cnpj, ticket_exibir_contato, ticket_exibir_codigo_barras
) VALUES (
    (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00'), 'Estaciona Parking', 20,
    12, 4, 2, 2,
    5.0, 3.0, 150.0,
    '80mm', TRUE, TRUE, TRUE
)
ON CONFLICT DO NOTHING;

-- 7.5 Tabela de Preços Inicial
INSERT INTO public.tabela_precos (
    empresa_id, primeira_hora, hora_adicional, diaria, mensal,
    tolerancia_minutos, fracionamento_minutos, tarifa_minima,
    valor_ticket_perdido, pernoite_valor, pernoite_a_partir_horas,
    carro_grande_primeira_hora, carro_grande_hora_adicional, carro_grande_diaria, carro_grande_mensal,
    moto_primeira_hora, moto_hora_adicional, moto_diaria, moto_mensal,
    caminhonete_primeira_hora, caminhonete_hora_adicional, caminhonete_diaria, caminhonete_mensal,
    ativo
) VALUES (
    (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00'), 5.0, 3.0, 30.0, 150.0,
    15, 60, 5.0,
    30.0, 40.0, 12,
    7.0, 4.0, 40.0, 190.0,
    3.0, 2.0, 20.0, 90.0,
    8.0, 5.0, 50.0, 220.0,
    TRUE
)
ON CONFLICT DO NOTHING;

-- 7.6 Formas de Pagamento Padrão
INSERT INTO public.formas_pagamento (nome, codigo, ativo, empresa_id)
VALUES
    ('Dinheiro', 'dinheiro', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00')),
    ('PIX', 'pix', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00')),
    ('Cartão de Crédito', 'cartao_credito', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00')),
    ('Cartão de Débito', 'cartao_debito', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00')),
    ('Convênio', 'convenio', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00')),
    ('Mensalista', 'mensalista', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00')),
    ('Cortesia', 'cortesia', TRUE, (SELECT id FROM public.empresas WHERE cnpj = '00.000.000/0001-00'))
ON CONFLICT (codigo) DO NOTHING;

-- 7.7 Tipos de Veículo Padrão
INSERT INTO public.tipos_veiculo (id, empresa_id, nome, ativo, primeira_hora, hora_adicional, diaria, mensal)
VALUES
    (1, 1, 'Carro', TRUE, 5.0, 3.0, 30.0, 150.0),
    (2, 1, 'Moto', TRUE, 3.0, 2.0, 20.0, 90.0),
    (3, 1, 'Carro Grande', TRUE, 7.0, 4.0, 40.0, 190.0),
    (4, 1, 'Caminhonete', TRUE, 8.0, 5.0, 50.0, 220.0)
ON CONFLICT (id) DO NOTHING;

-- 7.8 Permissões Padrão (RBAC) para Operador e Supervisor
INSERT INTO public.permissoes (perfil, modulo, acao) VALUES
    -- OPERADOR
    ('operador', 'operacao', 'ver'),
    ('operador', 'caixa', 'ver'),
    ('operador', 'caixa', 'criar'),
    ('operador', 'caixa', 'fechar_caixa'),
    ('operador', 'pagamentos', 'ver'),
    ('operador', 'pagamentos', 'criar'),
    ('operador', 'pagamentos', 'cancelar'),
    ('operador', 'formas_pagamento', 'ver'),
    ('operador', 'tabela_precos', 'ver'),
    ('operador', 'descontos', 'ver'),
    ('operador', 'cortesias', 'ver'),
    ('operador', 'cortesias', 'criar'),
    ('operador', 'mensalistas', 'ver'),
    ('operador', 'mensalistas', 'criar'),
    ('operador', 'mensalistas', 'editar'),
    ('operador', 'convenios', 'ver'),
    ('operador', 'contas_receber', 'ver'),
    ('operador', 'estornos', 'ver'),
    ('operador', 'auditoria', 'ver'),
    ('operador', 'dashboard_financeiro', 'ver'),
    ('operador', 'relatorios', 'ver'),
    ('operador', 'usuarios', 'ver'),
    ('operador', 'clientes', 'ver'),
    ('operador', 'clientes', 'criar'),
    ('operador', 'clientes', 'editar'),
    ('operador', 'configuracoes', 'ver'),
    ('operador', 'nfse', 'ver'),
    ('operador', 'lista_negra', 'ver'),
    ('operador', 'reservas', 'ver'),
    ('operador', 'reservas', 'criar'),
    ('operador', 'reservas', 'editar'),
    ('operador', 'ocorrencias', 'ver'),
    ('operador', 'ocorrencias', 'criar'),
    ('operador', 'notificacoes', 'ver'),
    -- SUPERVISOR
    ('supervisor', 'operacao', 'ver'),
    ('supervisor', 'caixa', 'ver'),
    ('supervisor', 'caixa', 'criar'),
    ('supervisor', 'caixa', 'editar'),
    ('supervisor', 'caixa', 'fechar_caixa'),
    ('supervisor', 'pagamentos', 'ver'),
    ('supervisor', 'pagamentos', 'criar'),
    ('supervisor', 'pagamentos', 'editar'),
    ('supervisor', 'pagamentos', 'cancelar'),
    ('supervisor', 'pagamentos', 'estornar'),
    ('supervisor', 'formas_pagamento', 'ver'),
    ('supervisor', 'formas_pagamento', 'criar'),
    ('supervisor', 'formas_pagamento', 'editar'),
    ('supervisor', 'tabela_precos', 'ver'),
    ('supervisor', 'tabela_precos', 'editar'),
    ('supervisor', 'descontos', 'ver'),
    ('supervisor', 'descontos', 'criar'),
    ('supervisor', 'descontos', 'editar'),
    ('supervisor', 'descontos', 'autorizar'),
    ('supervisor', 'cortesias', 'ver'),
    ('supervisor', 'cortesias', 'criar'),
    ('supervisor', 'cortesias', 'editar'),
    ('supervisor', 'cortesias', 'autorizar'),
    ('supervisor', 'mensalistas', 'ver'),
    ('supervisor', 'mensalistas', 'criar'),
    ('supervisor', 'mensalistas', 'editar'),
    ('supervisor', 'mensalistas', 'excluir'),
    ('supervisor', 'convenios', 'ver'),
    ('supervisor', 'convenios', 'criar'),
    ('supervisor', 'convenios', 'editar'),
    ('supervisor', 'convenios', 'excluir'),
    ('supervisor', 'contas_receber', 'ver'),
    ('supervisor', 'contas_receber', 'criar'),
    ('supervisor', 'contas_receber', 'editar'),
    ('supervisor', 'contas_receber', 'excluir'),
    ('supervisor', 'estornos', 'ver'),
    ('supervisor', 'estornos', 'criar'),
    ('supervisor', 'estornos', 'estornar'),
    ('supervisor', 'auditoria', 'ver'),
    ('supervisor', 'dashboard_financeiro', 'ver'),
    ('supervisor', 'relatorios', 'ver'),
    ('supervisor', 'usuarios', 'ver'),
    ('supervisor', 'usuarios', 'criar'),
    ('supervisor', 'usuarios', 'editar'),
    ('supervisor', 'clientes', 'ver'),
    ('supervisor', 'clientes', 'criar'),
    ('supervisor', 'clientes', 'editar'),
    ('supervisor', 'clientes', 'excluir'),
    ('supervisor', 'configuracoes', 'ver'),
    ('supervisor', 'nfse', 'ver'),
    ('supervisor', 'nfse', 'criar'),
    ('supervisor', 'nfse', 'cancelar'),
    ('supervisor', 'lista_negra', 'ver'),
    ('supervisor', 'lista_negra', 'criar'),
    ('supervisor', 'lista_negra', 'editar'),
    ('supervisor', 'lista_negra', 'excluir'),
    ('supervisor', 'reservas', 'ver'),
    ('supervisor', 'reservas', 'criar'),
    ('supervisor', 'reservas', 'editar'),
    ('supervisor', 'reservas', 'excluir'),
    ('supervisor', 'ocorrencias', 'ver'),
    ('supervisor', 'ocorrencias', 'criar'),
    ('supervisor', 'ocorrencias', 'editar'),
    ('supervisor', 'notificacoes', 'ver')
ON CONFLICT (perfil, modulo, acao) DO NOTHING;

-- 7.9 Atualização dos ponteiros de sequences para evitar erros de duplicate key
SELECT setval(pg_get_serial_sequence('public.empresas', 'id'), COALESCE(MAX(id), 1), COUNT(*) > 0) FROM public.empresas;
SELECT setval(pg_get_serial_sequence('public.perfis', 'id'), COALESCE(MAX(id), 1), COUNT(*) > 0) FROM public.perfis;
SELECT setval(pg_get_serial_sequence('public.usuarios', 'id'), COALESCE(MAX(id), 1), COUNT(*) > 0) FROM public.usuarios;
SELECT setval(pg_get_serial_sequence('public.clientes', 'id'), COALESCE(MAX(id), 1), COUNT(*) > 0) FROM public.clientes;
SELECT setval(pg_get_serial_sequence('public.financeiro', 'id'), COALESCE(MAX(id), 1), COUNT(*) > 0) FROM public.financeiro;

-- ==============================================================================
-- 8. RECARREGAR O CACHE DO POSTGREST
-- ==============================================================================
NOTIFY pgrst, 'reload schema';

-- FIM DO SCRIPT
